### ISSUE TITLE
[Feature Request] Export to csv

### ISSUE THREAD

**Issue by princepaul** [CroatiaControlLtd/asterix#139]
Can someone try to implement to export the data in csv with proper header so that the data can be analyzed in a better and simple way.

**Comment by acebrianjuan** [comment]
Hi @princepaul,

As far as my understanding about [CSV](https://en.wikipedia.org/wiki/Comma-separated_values) files goes, I see a few big challenges here:

How would you handle the intrinsically variable nature of the ASTERIX protocol data? I typically see CSV files used for data than can be structured in a tabular form, with a fixed number of columns (see an example [here](https://people.sc.fsu.edu/~jburkardt/data/csv/cities.csv)). For instance, can you think of a header that would allow to accommodate a variable number of Data Items for a given ASTERIX Category?

And what about if you are working with more than one Category at the same time (each Category having [its own specification](https://www.eurocontrol.int/library?keywords=asterix&sort_by=title&f%5B0%5D=topic%3A973&f%5B1%5D=topic%3A973&f%5B2%5D=topic%3A973))? How would you accommodate them all in the same CSV file?

Regards,
Álvaro

**Comment by filipjonckers** [comment]
My first Asterix decoder at Belgocontrol/skeyes "Panoramix" decoded every field in the Asterix stream and saved it into a SQLite database.
For each Asterix field there was a column in the database.  This approach could work for CSV.
Column header names should be the same as the field names in the Asterix doc.
A more elaborate option would be a selection of fields/columns before export.
This would be interesting if one would like to import the data into any database or excel for quick analysis

**Comment by acebrianjuan** [comment]
Hi @filipjonckers,

Thank you for insight.

> For each Asterix field there was a column in the database. This approach could work for CSV.
> Column header names should be the same as the field names in the Asterix doc.

I think I understand.
So you had as many columns in the database as fields described in the ASTERIX specification documents for each Category?

If that is the case, you probably had thousands of different columns if you handled different ASTERIX Categories in your database.
Is this correct?

Regards,
Álvaro

**Comment by princepaul** [comment]
Hi @acebrianjuan ,

I do agree that it is a challenge as same packet can have multiple types of messages and same type having different fields because of complexity of data. What about having every header field a unique name like 048_010_SAC, 010_010_SAC by adding the type of CAT as a prefix to field name? As you asked @filipjonckers , yes it will create numerous columns.

csv is very easy to import for filtering, for eg, if you want to check only the information pertaining to one Track number or one Callsign.

Else a mechanism to convert the generated xml/json to csv can also be thought of.

**Comment by ifsnop** [comment]
HI!

During my early days at Enaire, I did more or less the same, then migrate
to mysql. Problem arised when decoding compound or reped data items, I need
to separate them with ; inside each column.

Mongodb would fit perfectly for a job like this, where there is no schema
defined.

Currently I only consume data items that I need, and use JSON for the
intermediate steps.

btw, great to hear from a Panoramix developer, I think I hear about it in
the SUGCT meetings, long time ago.

**Comment by filipjonckers** [comment]
Just to clarify - a database table would only contain one asterix category - so the table format for cat48 would only contain cat48 fields while a table containing cat62 would only contain fields in cat62 :-)
Indeed, one single table supporting all categories would be thousands of columns which is not a good idea.
Elasticsearch or other more "modern" approaches using json are now a better way to go ....
Nice to hear @ifsnop !
The Panoramix SQLite databases were vital in analysis of Mode S data for anomalies which were then reported in the Eurocontrol AMS database.  I loved hunting for Mode S anomalies and catched quite a few major ones.
In the meantime I moved on from surveillance to the ATM systems: Eurocat adaptation & support and now MUAC SAS ...

**Comment by Zoran3172** [comment]
Hello everyone,
First of all, this is a great code for ASTERIX decoding and I am a new on GitHub, and new in python programming language.
I tried to use this library one month ago, and actually made a decision to leave all of my previous decoders (written in MATLAB and C (not C++)). Fortunately, python is a very intuitive language, so I learned it enough for using this library. As I can see, I had the same needs as other users, i.e. CSV presentation of decoded data. In all of mine decoders I have used CSV as final format for data analysis. So, I have used my modest python knowledge (few days of reading) to write some simple code for conversion from list of dictionaries to CSV. I have used python 2.7. Firstly, I had to realize how data were packed into lists/dictionaries - especially variable, compound, repetitive. When I figured out, I wrote this simple code (You can treat it as the beginner code). During the testing I noticed the following:
1. Some of data items in XML had duplicated names (spare - not important because value is 0, res, ...), and those items were overwritten in output list. So, I changed the names by giving them suffix res1, res2,  etc. As I can see this is already noticed and corrected
2. Variable items: If there is e.g. one octet, followed by one octet extensions (lets assume that extensions are coded in the same way as first octet), in the output list only the last octet will be decoded. I suppose the reason is the same as for the point 1, i.e. data is overwritten because of the same names. Maybe I am wrong, but I tested it and compared with other applications. It will be a good idea to write those variable decoded data octets in list, as it is done for repetitive items. The workaround that I did was the changing of XML. I copied the fixed part of variable as many times as i need and renamed the new items with suffix 1, 2, ...
3.  Compound: Only the present data is shown (in older version all data were there, presence bit(s)+values)
4. repetitive: good idea, because they are packed into list, there is no information what is the REP value, but it can be concluded according to size of list. I suggest that variable items be decoded and written in the same way.

So, I wrote a code for conversion from list of decoded items to CSV file. I dont know what is the best way to share it, but I will do it here for category 48 (CAT_048.py + modified XML for cat 48 and BDS + clear_None.py). For the non-presence items i have used 'None' value as default, but you can change to what ever you want (np.NaN, empty, default ...). The if statements can be avoid by using get methods. In case of variable only the first octet will be shown, or even the second, if it is defined in XML, but that will be the real data, not overwritten (please compare the original and my version of xml). For repetitive data, REP value will be shown and the first three data. For the BDS, 40/50/60 will be decoded, while additional three non-extracted (HEX) BDS registers will be shown. At the end, for one hour of recording the output file could reach 400 MB, so I have included the clear_None.py for conversion to CSV where all None are converted to empty strings, and all columns (data Items) with all None valuesare deleted. This can reduce file size up to 5 (in real environment).    

I hope that this can be helpful.

Once more time, many thanks to author and all contributors, this is a very good tool. It will bi perfect to have it on Windows and this python form.
 
The link: 
[CSV.zip](https://github.com/CroatiaControlLtd/asterix/files/5050376/CSV.zip)

**Comment by princepaul** [comment]
@Zoran3172,

Wow..!!
Thanks for the head up. Will test it and revert.
