### ISSUE TITLE
Hexdata presentation is not correct for multiple records in block

### ISSUE THREAD

**Issue by dsalantic** [CroatiaControlLtd/asterix#171]
For Asterix data blocks with multiple records (for Asterix specification before edition 2.1) hexdata presentation is not correct.
Hexdata must be fixed to show only record bytes without CAT and LEN bytes.
This changes the CRC calculation also, because only data must be used for calculation and not CAT and LEN.

**Comment by ifsnop** [comment]
In your patch, you create a hexdata string:
~~~
format("\nHexData: %02X%02X%02X", m_pCategory->m_id, ((m_nLength + 3) >> 8) & 0xff, (m_nLength + 3) & 0xff);
~~~
and modify the crc calculation not to include category and length. So now if you want to recreate the crc, you have to take into account special considerations (strip cat&length from hexdata, for example). Anyway, this is not a big deal.

I think crc should include both (category and length), since both are added after being calculated from the datarecord being decoded. hexdata presentation is correct (it was made specially to work with pre 2.1 specs)

Also, adding category and length makes very difficult that two different datarecords can have the same crc. It is easier to forge a packet with same crc adding bytes, but near impossible to make same crc with same length but different content.

>This changes the CRC calculation also, because only data must be used for calculation and not CAT and LEN.

Is this affirmation supported somewhere?

**Comment by dsalantic** [comment]
Thanks for your remarks, but let me explain what was the issue I received from one user who was using asterix data from pre 2.1 spec.

In pre 2.1 specs format of Data block is following:
CAT
LEN
RECORD
RECORD
RECORD
....


In post 2.1 specs there are no Data blocks (or we can look at it as Data block can contain only one Data Record):
CAT 
LEN
RECORD

In previous version of asterix parser it was like this:
For post 2.1 specs:
Each record has:
HEXDATA=CAT,LEN,DATA
CRC=CRC(CAT,LEN,DATA)

And it is OK, but for pre 2.1 specs it was:
DATABLOCK=CAT,BLOCKLEN,RECORD1DATA,RECORD2DATA
HEXDATA of 1st record=CAT,RECORD1LEN,RECORD1DATA
CRC of 1st record=CRC(CAT,RECORD1LEN,RECORD1DATA)
HEXDATA of 2nd record=CAT,RECORD2LEN,RECORD2DATA
CRC of 2nd record=CRC(CAT,RECORD2LEN,RECORD2DATA)

So, the confusing part was that in HEXDATA of each record you get RECORDLEN which is not present in original data. On top of it we calculate CRC based on data (RECORDLEN) that is not known until you parse the data record.

For me the most obvious way how to fix that (and the easiest) was to remove CAT and LEN from HEXDATA and from CRC calculation. It makes the HEX data for pre 2.1 spec clear.

I understand that it changed CRC calculation for post 2.1 specs which was not necessary, but it's a price for making both versions parsing consistent.

If you have any suggestions how to change it to work for both versions let me know.

**Comment by ifsnop** [comment]
I've been using the version with this patch applied. Main problem is that now, hexdata by itself is not enough to recreate the asterix message. You need you manually build category from the CATXXX json key and use the length value.

For me is better to have a complete hexdata, but as a solution, maybe you could made available the category in a json value (and not only in a key, which is confusing when parsing)?

>So, the confusing part was that in HEXDATA of each record you get RECORDLEN which is not present in original data. On top of it we calculate CRC based on data (RECORDLEN) that is not known until you parse the data record.

RECORD2LEN is not present in the original data , but indeed very useful to have it calculated, so you now have a post2.1 specs converted for free from a pre2.1 specs, and can access faster to the datablock.

**Comment by ifsnop** [comment]
If you have a complete hexdata, anyone can build an asterix filter with a couple of bash commands, and then send the datablock again after being reconstructed from the hexdata value. If cat&length are stripped, that complicates the build.

pd.- I use jq to parse json from asterix and filter/print/resend/store the matching datablocks.
