### ISSUE TITLE
inconsistent timestamp

### ISSUE THREAD

**Issue by ifsnop** [CroatiaControlLtd/asterix#54]
Timestamp is defined as seconds since midnight 1/1/1970, but truncated to seconds since current midnight day.

Definition in DataBlock.h
~~~
class DataBlock
{
public:
  DataBlock(Category* cat, unsigned long len, const unsigned char* data, unsigned long nTimestamp = 0, uint32_t nCrc = 0);
  virtual
  ~DataBlock();

  Category* m_pCategory;
  unsigned long m_nLength;
  unsigned long m_nTimestamp; // Date and time when this packet was captured. This value is in seconds since January 1, 1970 00:00
  uint32_t m_nCrc;
  bool m_bFormatOK;
~~~

Creation in asterixrawsubformat.cxx

~~~
 // get current timstamp in ms since midnight
        struct timeval tp;
        gettimeofday(&tp, NULL);
        unsigned long nTimestamp = (tp.tv_sec % 86400) * 1000 + tp.tv_usec / 1000;
~~~

I think is better to have a unique timestamp, since there I usually have recordinds that spans throught midnight.

Is there any reason for truncating it?

Thanks in advance.

**Comment by ifsnop** [comment]
Will you accept a PR that converts timestamp to float, with number of seconds since 1970?

**Comment by dsalantic** [comment]
We truncated timestamp because in some formats we only have time since midnight (e.g. in final format).
But, you are right, it would be best to have number of seconds since 1970 in float (so we will also have  milliseconds). For formats without date it will be set to 1.1.1970.
If you are willing to change it, I can merge it to master branch.
Note that recently I implemented many changes to source code to enable Python integration, so please use latest source if possible.
Thanks

**Comment by ifsnop** [comment]
Finally got some time to spend on this task. Please see commit #182
