### ISSUE TITLE
Ethereal/wireshark plugin not working since v2.3.0

### ISSUE THREAD

**Issue by koutcher** [CroatiaControlLtd/asterix#60]
Commit ea013136e73a98a7ec38a696095817e715bb4282 is breaking the ethereal/wireshark plugin. 

As m_pDefinition is not allocated within class InputParser, it doesn't feel correct to delete it in InputParser's destructor.

**Comment by dsalantic** [comment]
Thanks for the info, but unfortunatelly I stopped supporting the asterix plugin for ethereal/wireshark some time ago.
The reason is that it became too complicated to build latest wireshark, and besides that, now there is an Asterix dissector already built in the official Wireshark release so I use it instead (https://wiki.wireshark.org/ASTERIX).
Anyway, if you need it, feel free to update a fix and I'll include it in master release if it does not affect the rest of the code.

**Comment by koutcher** [comment]
It's like working for Ferrari and driving a Fiat to go back home :-) I noticed the Asterix dissector in the latest Wireshark but RHEL still ships with 1.10 so I keep building the plugin from yours. Moreover I prefer the XML definitions which can be easily extended or audited. 

To fix v2.3.0, I simply reverted the commit mentioned above.

**Comment by dsalantic** [comment]
Good point :-).
OK, if this change is the only problem, I'll try to fix it, and will try to keep ethereal plugin live as long as possible.

**Comment by ifsnop** [comment]
Maybe m_pDefinition could be allocated from within class InputParser as a solution to both problems? I think that the destructor is the place to remove members of the class.
