### ISSUE TITLE
How to decode cat7 and cat48 extension field ? It’s not working for me.

### ISSUE THREAD

**Issue by fnj-github** [CroatiaControlLtd/asterix#76]
I don’t have cat7 and cat48 extension field decoding. It’s not working for me. Can you help me?

**Comment by dsalantic** [comment]
You need to create XML with the definition of required category.
See in install/config folder where all categories defined.
Unfortunatelly CAT007 is not implemented, but if you look how other categories are defined it shouldn't have to be a problem to implement XML for CAT007, because many data are identical to other categories.
I'm not sure about which extension field in CAT048 you are talking (is it SP or RE field?). If yes, then you need to implement it also, depending of your needs. Those extensions are not standardized.

If you implement new categories by yourself please send it to me (and if possible a sample of your recordings for test) and I will include it in official repository.
